
| Loading Grails 2.1.1
| Configuring classpath
| Configuring classpath.
| Environment set to test
| Environment set to test.
| Environment set to test..
| Environment set to test...
| Environment set to test....
| Environment set to test.....
| Compiling 2 source files
| Compiling 2 source files.
| Compiling 2 source files..
| Compiling 1 source files
| Compiling 1 source files.
Skipping Config.groovy overrides: null/dataExport-commons-config.groovy and C:\Users\dlahr/.grails/dataExport/dataExport-commons-config.groovy not found
Skipping Config.groovy overrides: null/dataExport-test-config.groovy and C:\Users\dlahr/.grails/dataExport/dataExport-test-config.groovy not found
| Compiling 1 source files..
| Compiling 1 source files...
| Compiling 1 source files....
| Compiling 1 source files.....
| Packaging Grails application
| Packaging Grails application.
| Compiling 1 source files
| Compiling 1 source files.
Skipping Config.groovy overrides: null/dataExport-commons-config.groovy and C:\Users\dlahr/.grails/dataExport/dataExport-commons-config.groovy not found
Skipping Config.groovy overrides: null/dataExport-test-config.groovy and C:\Users\dlahr/.grails/dataExport/dataExport-test-config.groovy not found
| Compiling 1 source files..
| Compiling 1 source files...
| Compiling 1 source files....
| Compiling 1 source files.....
| Running Grails application
[10:56:30,322 ERROR org.hibernate.util.JDBCExceptionReporter]  Table "ELEMENT" not found; SQL statement:
select this_.ELEMENT_ID as ELEMENT1_24_0_, this_.version as version24_0_, this_.abbreviation as abbrevia3_24_0_, this_.BARD_URI as BARD4_24_0_, this_.date_created as date5_24_0_, this_.description as descript6_24_0_, this_.element_status as element7_24_0_, this_.EXTERNAL_URL as EXTERNAL8_24_0_, this_.label as label24_0_, this_.last_updated as last10_24_0_, this_.modified_by as modified11_24_0_, this_.ready_for_extraction as ready12_24_0_, this_.synonyms as synonyms24_0_, this_.unit as unit24_0_ from element this_ [42102-164]
[10:56:30,328 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/dataExport]]  Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [select this_.ELEMENT_ID as ELEMENT1_24_0_, this_.version as version24_0_, this_.abbreviation as abbrevia3_24_0_, this_.BARD_URI as BARD4_24_0_, this_.date_created as date5_24_0_, this_.description as descript6_24_0_, this_.element_status as element7_24_0_, this_.EXTERNAL_URL as EXTERNAL8_24_0_, this_.label as label24_0_, this_.last_updated as last10_24_0_, this_.modified_by as modified11_24_0_, this_.ready_for_extraction as ready12_24_0_, this_.synonyms as synonyms24_0_, this_.unit as unit24_0_ from element this_]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:118)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4791)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [select this_.ELEMENT_ID as ELEMENT1_24_0_, this_.version as version24_0_, this_.abbreviation as abbrevia3_24_0_, this_.BARD_URI as BARD4_24_0_, this_.date_created as date5_24_0_, this_.description as descript6_24_0_, this_.element_status as element7_24_0_, this_.EXTERNAL_URL as EXTERNAL8_24_0_, this_.label as label24_0_, this_.last_updated as last10_24_0_, this_.modified_by as modified11_24_0_, this_.ready_for_extraction as ready12_24_0_, this_.synonyms as synonyms24_0_, this_.unit as unit24_0_ from element this_]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:635)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
	at org.springframework.orm.hibernate3.HibernateTemplate.executeFind(HibernateTemplate.java:343)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ListPersistentMethod.doInvokeInternal(ListPersistentMethod.java:56)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:72)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:65)
	at org.codehaus.groovy.grails.commons.metaclass.StaticMethodInvocation$invoke.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi.list(HibernateGormEnhancer.groovy:318)
	at bard.db.dictionary.Element.list(Element.groovy)
	at bard.db.dictionary.Element$list.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at BootStrap$_closure1.doCall(BootStrap.groovy:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:945)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
	at groovy.lang.Closure.call(Closure.java:415)
	at groovy.lang.Closure.call(Closure.java:409)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:301)
	at grails.util.Environment.executeForEnvironment(Environment.java:294)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:270)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:74)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:105)
	... 11 more
Caused by: org.hibernate.exception.SQLGrammarException: could not execute query
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.loader.Loader.doList(Loader.java:2545)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
	at org.hibernate.loader.Loader.list(Loader.java:2271)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:119)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1716)
	at org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:347)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ListPersistentMethod$1.doInHibernate(ListPersistentMethod.java:76)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
	... 46 more
Caused by: org.h2.jdbc.JdbcSQLException: Table "ELEMENT" not found; SQL statement:
select this_.ELEMENT_ID as ELEMENT1_24_0_, this_.version as version24_0_, this_.abbreviation as abbrevia3_24_0_, this_.BARD_URI as BARD4_24_0_, this_.date_created as date5_24_0_, this_.description as descript6_24_0_, this_.element_status as element7_24_0_, this_.EXTERNAL_URL as EXTERNAL8_24_0_, this_.label as label24_0_, this_.last_updated as last10_24_0_, this_.modified_by as modified11_24_0_, this_.ready_for_extraction as ready12_24_0_, this_.synonyms as synonyms24_0_, this_.unit as unit24_0_ from element this_ [42102-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.readTableOrView(Parser.java:4753)
	at org.h2.command.Parser.readTableFilter(Parser.java:1080)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1686)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1793)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1680)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1523)
	at org.h2.command.Parser.parseSelect(Parser.java:1511)
	at org.h2.command.Parser.parsePrepared(Parser.java:405)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1121)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:239)
	at $Proxy16.prepareStatement(Unknown Source)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452)
	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
	at org.hibernate.loader.Loader.doQuery(Loader.java:801)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
	at org.hibernate.loader.Loader.doList(Loader.java:2542)
	... 53 more
[10:56:30,339 ERROR org.apache.catalina.core.StandardContext]  Error listenerStart
[10:56:30,344 ERROR org.apache.catalina.core.StandardContext]  Context [/dataExport] startup failed due to previous errors
| Server running. Browse to http://localhost:8080/dataExport
| Running 39 spock tests...
| Running 39 spock tests... 1 of 39
| Failure:  test GET dictionary success(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 2 of 39
| Failure:  test GET unauthorized(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 3 of 39
| Failure:  test GET dictionary fail with wrong Accept Header(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 4 of 39
| Failure:  test result Type 404 not Found(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 5 of 39
| Failure:  test result Type 400 not bad request(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 6 of 39
| Failure:  test GET Result Type Success(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 7 of 39
| Failure:  test Stage 404 not Found(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 8 of 39
| Failure:  test Stage 400 not bad request(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 9 of 39
| Failure:  test GET Stage Success(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 10 of 39
| Failure:  test Element 404 not Found(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 11 of 39
| Failure:  test Element 400 not bad request(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 12 of 39
| Failure:  test GET Element Success(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 13 of 39
| Failure:  test Update Element Success(dataexport.dictionary.DictionaryRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.DictionaryRestControllerFunctionalSpec.$spock_initializeFields(DictionaryRestControllerFunctionalSpec.groovy:31)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 14 of 39
| Failure:  test GET Root Elements(dataexport.dictionary.RootRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.RootRestControllerFunctionalSpec.$spock_initializeFields(RootRestControllerFunctionalSpec.groovy:25)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 15 of 39
| Failure:  test GET root fail with wrong Accept Header(dataexport.dictionary.RootRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.dictionary.RootRestControllerFunctionalSpec.$spock_initializeFields(RootRestControllerFunctionalSpec.groovy:25)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 16 of 39
| Failure:  test GET Experiments success(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 17 of 39
| Failure:  test GET unauthorized(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 18 of 39
| Failure:  test GET experiment fail with wrong Accept Header(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 19 of 39
| Failure:  test experiment 404 not Found(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 20 of 39
| Failure:  test experiment 400 not bad request(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 21 of 39
| Failure:  test GET Experiment Success(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 22 of 39
| Failure:  test Update Experiment Success(dataexport.experiment.ExperimentRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ExperimentRestControllerFunctionalSpec.$spock_initializeFields(ExperimentRestControllerFunctionalSpec.groovy:28)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 23 of 39
| Failure:  test GET projects success(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 24 of 39
| Failure:  test GET unauthorized(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 25 of 39
| Failure:  test GET project fail with wrong Accept Header(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 26 of 39
| Failure:  test project 404 not Found(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 27 of 39
| Failure:  test experiments 400 not bad request(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 28 of 39
| Failure:  test GET Project Success(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 29 of 39
| Failure:  test Update Project Success(dataexport.experiment.ProjectRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.experiment.ProjectRestControllerFunctionalSpec.$spock_initializeFields(ProjectRestControllerFunctionalSpec.groovy:27)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 30 of 39
| Failure:  test GET assays success(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 31 of 39
| Failure:  test GET unauthorized(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 32 of 39
| Failure:  test GET assays fail with wrong Accept Header(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 33 of 39
| Failure:  test assay 404 not Found(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 34 of 39
| Failure:  test assay 400 not bad request(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 35 of 39
| Failure:  test GET Assay Success(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 36 of 39
| Failure:  test Assay Document 404 not Found(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 37 of 39
| Failure:  test assay doc 400 not bad request(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 38 of 39
| Failure:  test GET Assay document Success(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Running 39 spock tests... 39 of 39
| Failure:  test Update Assay Success(dataexport.registration.AssayRestControllerFunctionalSpec)
|  groovyx.remote.RemoteControlException: Error sending command chain to 'http://localhost:8080/dataExport/grails-remote-control'
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:65)
	at groovyx.remote.client.RemoteControl.sendCommandChain(RemoteControl.groovy:79)
	at groovyx.remote.client.RemoteControl.exec(RemoteControl.groovy:67)
	at groovyx.remote.client.RemoteControl.call(RemoteControl.groovy:71)
	at dataexport.registration.AssayRestControllerFunctionalSpec.$spock_initializeFields(AssayRestControllerFunctionalSpec.groovy:33)
Caused by: java.io.FileNotFoundException: http://localhost:8080/dataExport/grails-remote-control
	at groovyx.remote.transport.http.HttpTransport.send_closure1(HttpTransport.groovy:62)
	at groovyx.remote.transport.http.HttpTransport.send(HttpTransport.groovy:53)
	... 4 more
| Completed 39 spock tests, 39 failed in 2335ms
| Server stopped
| Tests FAILED  - view reports in C:\Local\code_and_repos\BARD\dataExport\target\test-reports
